server:
  address:     ":8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  errorStack: false
  errorLogEnabled: false
  errorLogPattern: "error-{Ymd}.log"

logger:
  path: "./log/"
  file: "{Y-m-d}.log"
  prefix: ""
  level: "info"
  timeFormat: "2006-01-02 15:04:05"
  ctxKeys: ["req","TraceId"]
  header: true
  stSkip: 0
  stdout: true
  rotateSize: 0
  rotateExpire: 0
  rotateBackupLimit: 0
  rotateBackupExpire: 0
  rotateBackupCompress: 0
  rotateCheckInterval: "1h"
  stdoutColorDisabled: false
  writerColorEnable: false
  flags: 92

database:
  host: "127.0.0.1"
  port: "5432"
  user: "admin"
  password: "admin123"
  dbname: "auth-service"
  sslmode: "disable"
  max_open_conns: 150
  max_idle_conns: 10
  conn_max_lifetime: 1
  logger:
    level: "error"
    stdout: true
  debug: true


redis:
  default:
    address: 127.0.0.1:6379
    password: "redispass"
    db: 0
    idleTimeout: "60s"
    maxConnLifetime: "90s"
    waitTimeout: "60s"
    dialTimeout: "30s"
    readTimeout: "30s"
    writeTimeout: "30s"
    maxActive: 10000

auth:
  secretKey: +hd>PywO8jrAnIewJvK7U[bU1;*28m
  accessTokenExpireMinute: 60
  refreshTokenExpireMinute: 1440

email:
  mailjet_api_key: ${MAILJET_API_KEY}
  mailjet_secret_key: ${MAILJET_SECRET_KEY}
  from_email: bitzapofficial@gmail.com
  from_name: Bitzap Official
  app_url: localhost:8080
